# Assignment 5: Visualizing Rhode Island

This assignment will have you critique and generate visualizations of datasets related to our wonderful tiny state, Rhode Island. The learning goals of this assignment are to:

(a) practice analyzing data visualizations using the concepts and terminology we learned in class, such as the grammar of graphics (marks, attributes, encoding, etc.), levels of measurement (nominal, ordinal, quantitative variables), and principles of perception (magnitude estimation, preattentive processing, etc.).

(b) gain experience working with a grammar-of-graphics data visualization API, Altair.

In [ ]:
import altair as alt
import a5

# Part A. Datasets

## Dunkin' Donuts Across the US

For this assignment, we'll be using two datasets. The first is a dataset of about Dunkin' Donuts storefronts across the United States.

In [ ]:
dunkins = a5.load_dunkins()
dunkins

,state,region,store_count,stores_per_100k,stores_per_sqmi,avg_sat_delivery_hours,frac_loyalty
0,AK,West,2,0.272700,0.000004,24.000000,0.500000
1,AL,South,73,1.429000,0.001441,11.760274,0.808219
2,AR,South,16,0.521558,0.000307,8.906250,0.937500
3,AZ,West,117,1.574412,0.001030,12.820513,0.940171
4,CA,West,158,0.405490,0.001014,11.996835,0.924051
5,CO,West,54,0.918741,0.000521,10.620370,0.907407
6,CT,Northeast,478,13.192193,0.098720,13.961297,0.970711
7,DC,South,21,3.092911,0.344262,5.547619,0.857143
8,DE,South,72,6.976846,0.036942,13.583333,0.986111
9,FL,South,936,4.139628,0.017455,14.284722,0.961538
10,GA,South,320,2.901382,0.005564,14.206250,0.915625
11,HI,West,6,0.416610,0.000934,6.166667,0.833333
12,IA,Midwest,37,1.153725,0.000662,10.810811,0.864865
13,IL,Midwest,733,5.840782,0.013203,15.225102,0.960437
14,IN,Midwest,142,2.069308,0.003964,13.373239,0.915493
15,KS,Midwest,26,0.884190,0.000318,11.942308,0.923077
16,KY,South,69,1.524473,0.001747,11.485507,0.913043
17,LA,South,21,0.459142,0.000486,8.785714,0.619048
18,MA,Northeast,1033,14.714978,0.132436,13.371733,0.975799
19,MD,South,337,5.452851,0.034717,13.565282,0.946588
20,ME,Northeast,160,11.463601,0.005188,12.990625,0.962500
21,MI,Midwest,136,1.354951,0.002405,14.176471,0.926471
22,MN,Midwest,47,0.819113,0.000590,11.531915,0.893617
23,MO,Midwest,58,0.936064,0.000844,10.586207,0.913793
24,MS,South,16,0.544207,0.000341,8.531250,0.812500
25,NC,South,246,2.270317,0.005060,12.272358,0.910569
26,NE,Midwest,25,1.263661,0.000325,13.460000,1.000000
27,NH,Northeast,215,15.334645,0.024014,12.248837,0.958140
28,NJ,Northeast,867,9.328104,0.117895,14.104383,0.972318
29,NM,West,26,1.232221,0.000214,10.000000,0.769231
30,NV,West,47,1.471428,0.000428,10.319149,0.765957
31,NY,Northeast,1471,7.516140,0.031214,13.876615,0.953093
32,OH,Midwest,312,2.647223,0.007636,13.618590,0.926282
33,OK,South,23,0.567366,0.000335,14.326087,1.000000
34,PA,Northeast,674,5.199942,0.015039,13.301929,0.967359
35,RI,Northeast,158,14.397943,0.152805,13.977848,0.993671
36,SC,South,137,2.549523,0.004557,11.080292,0.868613
37,TN,South,160,2.245145,0.003880,13.615625,0.931250
38,TX,South,270,0.885150,0.001034,12.442593,0.888889
39,UT,West,6,0.175555,0.000073,6.833333,1.000000
40,VA,South,261,2.994597,0.006609,11.710728,0.888889
41,VT,Northeast,49,7.563853,0.005316,12.244898,0.979592
42,WI,Midwest,118,1.996293,0.002173,14.483051,0.932203
43,WV,South,44,2.485776,0.001830,12.636364,0.863636
44,WY,West,3,0.513648,0.000031,1.666667,1.000000

This dataset contains seven columns:
* `state`: two-letter abbreviation of a US state.
* `region`: the region of the country the US state is in, e.g., Northeast for RI.
* `store_count`: the number of stores in the given state.
* `stores_per_100k`: the number of stores per 100,000 residents of the state.
* `stores_per_sqmi`: the number of stores per square mile in the state.
* `avg_sat_delivery_hours`: the average number of hours delivery is available on Saturdays.
* `frac_loyalty`: the fraction of storefronts that support the Dunkins loyalty program.

## Life Expectancy in Rhode Island

The second dataset provides county-level statistics about life expectancy and potential correlates in Rhode Island.

In [ ]:
life = a5.load_ri_life()
life

,county,geometry,rural_urban,life_expectancy,asmr,asmr_rank,rent,gini,pct_food_desert,fast_food,pct_farmers_market,pct_less_hs,pct_bachelors
0,West Greenwich,"POLYGON ((-71.787 41.65612, -71.78699 41.65599...",Rural,78.65,1029.60,36,1341,0.4168,0.00,0.23,22.48,5.1,31.0
1,Central Falls,"POLYGON ((-71.3943 41.89765, -71.39724 41.8967...",Urban,78.26,970.74,33,774,0.4557,0.00,37.20,0.00,48.2,7.4
2,Scituate,"POLYGON ((-71.69101 41.85646, -71.68908 41.844...",Rural,81.43,807.14,6,932,0.3981,0.00,0.13,61.14,9.3,28.3
3,Foster,"POLYGON ((-71.79469 41.85441, -71.79448 41.849...",Rural,79.14,813.75,8,908,0.4325,0.00,0.08,0.00,8.1,29.9
4,Burrillville,"POLYGON ((-71.60673 42.01341, -71.6616 42.0121...",Rural,77.33,1052.02,37,843,0.4087,57.56,0.37,96.13,17.4,22.8
5,Bristol,"POLYGON ((-71.29534 41.70721, -71.29122 41.702...",Urban,80.94,852.95,15,892,0.4563,53.84,3.04,71.82,18.7,32.5
6,East Greenwich,"POLYGON ((-71.54711 41.66185, -71.54704 41.659...",Rural,82.17,782.78,3,881,0.5041,54.52,1.76,45.31,3.5,58.9
7,East Providence,"POLYGON ((-71.37502 41.85745, -71.37233 41.850...",Urban,79.61,920.91,25,823,0.4378,20.39,7.72,33.22,20.8,22.8
8,Richmond,"POLYGON ((-71.71502 41.5542, -71.71401 41.5528...",Rural,78.43,1072.26,38,739,0.3460,0.00,0.42,96.73,8.5,33.0
9,Cumberland,"POLYGON ((-71.48736 41.97908, -71.48616 41.978...",Urban,81.50,799.52,4,859,0.4083,39.28,1.90,0.00,14.3,33.6
10,Providence,"POLYGON ((-71.47246 41.83698, -71.47243 41.834...",Urban,78.37,973.77,34,913,0.5339,5.31,25.58,81.09,27.4,29.0
11,Narragansett,"POLYGON ((-71.5228 41.37669, -71.52016 41.3765...",Rural,82.00,799.92,5,1113,0.4766,46.78,1.63,32.95,4.0,52.2
12,Warwick,"MULTIPOLYGON (((-71.44238 41.66361, -71.44302 ...",Urban,78.89,959.59,31,990,0.4162,33.34,4.82,16.78,10.2,29.0
13,Warren,"POLYGON ((-71.2844 41.76201, -71.28659 41.7424...",Urban,79.94,906.42,22,875,0.4636,96.83,5.48,0.00,16.5,28.2
14,Cranston,"POLYGON ((-71.46366 41.80505, -71.46603 41.803...",Urban,81.32,819.72,9,967,0.4340,25.34,4.85,30.56,14.9,29.7
15,Johnston,"POLYGON ((-71.49554 41.86898, -71.50509 41.867...",Urban,79.40,939.39,28,881,0.4252,29.00,2.55,73.09,18.2,21.6
16,Lincoln,"POLYGON ((-71.49079 41.94324, -71.48917 41.938...",Urban,81.26,835.33,12,848,0.4257,48.34,1.97,16.12,12.8,36.1
17,Woonsocket,"POLYGON ((-71.52893 42.01497, -71.52999 42.011...",Urban,75.85,1127.58,39,763,0.4570,29.41,10.43,54.92,27.7,12.9
18,Jamestown,"MULTIPOLYGON (((-71.34628 41.53417, -71.34591 ...",Rural,80.83,893.34,17,1403,0.4719,57.35,0.63,0.00,2.3,59.4
19,Tiverton,"POLYGON ((-71.21674 41.62559, -71.21531 41.625...",Rural,81.16,830.02,10,964,0.4118,57.17,0.69,79.11,13.9,29.9
20,Charlestown,"POLYGON ((-71.73125 41.39851, -71.73088 41.390...",Rural,80.75,844.02,13,1093,0.4511,0.00,0.37,99.28,8.2,35.4
21,Exeter,"POLYGON ((-71.78936 41.59685, -71.79051 41.571...",Rural,79.59,897.68,20,903,0.3591,0.00,0.14,85.53,7.5,45.6
22,Middletown,"POLYGON ((-71.30161 41.56203, -71.30365 41.559...",Rural,80.26,893.38,18,1157,0.4204,32.90,3.20,34.46,6.7,38.4
23,Glocester,"POLYGON ((-71.79765 41.92865, -71.79716 41.916...",Rural,80.09,848.50,14,820,0.3387,0.00,0.28,82.59,8.7,30.0
24,Little Compton,"POLYGON ((-71.21172 41.54545, -71.20683 41.543...",Rural,81.32,812.48,7,1317,0.4586,0.00,0.14,51.52,8.2,48.9
25,Newport,"MULTIPOLYGON (((-71.32757 41.45287, -71.32689 ...",Urban,79.52,917.56,24,1123,0.4575,8.63,8.70,66.17,9.7,48.2
26,South Kingstown,"POLYGON ((-71.62562 41.36076, -71.62416 41.361...",Rural,81.34,833.63,11,1035,0.4410,47.06,0.79,54.02,6.7,51.3
27,Portsmouth,"MULTIPOLYGON (((-71.28802 41.64558, -71.28816 ...",Urban,82.93,727.48,2,1336,0.4584,67.18,0.98,89.92,7.3,47.4
28,North Providence,"POLYGON ((-71.49554 41.86898, -71.49295 41.867...",Urban,79.91,872.42,16,930,0.4218,33.78,10.78,61.71,15.0,24.8
29,Pawtucket,"POLYGON ((-71.4219 41.8787, -71.41988 41.86977...",Urban,78.94,946.90,30,807,0.4525,5.64,14.68,50.63,24.3,18.9
30,Barrington,"POLYGON ((-71.31792 41.77616, -71.31995 41.774...",Urban,83.13,722.01,1,1340,0.4664,29.48,1.18,59.50,4.4,63.4
31,Hopkinton,"POLYGON ((-71.79767 41.41691, -71.79632 41.416...",Rural,78.90,916.36,23,731,0.3627,0.00,0.20,71.06,6.9,25.4
32,Westerly,"POLYGON ((-71.79767 41.41691, -71.79768 41.416...",Rural,79.64,901.35,21,918,0.4309,21.44,1.83,99.57,13.9,30.0
33,North Smithfield,"POLYGON ((-71.60673 42.01341, -71.60044 41.983...",Rural,79.40,927.55,27,925,0.4000,58.20,0.74,16.14,14.5,29.3
34,West Warwick,"POLYGON ((-71.53429 41.73017, -71.53406 41.722...",Urban,77.79,985.23,35,920,0.3944,15.86,7.49,36.43,15.0,21.0
35,Smithfield,"POLYGON ((-71.59031 41.93366, -71.58189 41.894...",Urban,80.34,923.54,26,948,0.4200,77.28,1.73,71.34,9.1,33.6
36,Coventry,"POLYGON ((-71.78969 41.7252, -71.78968 41.7247...",Rural,79.31,963.18,32,867,0.4042,49.33,0.72,0.70,11.2,25.4
37,North Kingstown,"POLYGON ((-71.52243 41.60257, -71.5219 41.6008...",Urban,80.34,945.22,29,934,0.4497,44.07,1.07,19.89,6.9,45.2
38,New Shoreham,"POLYGON ((-71.61313 41.16028, -71.61157 41.153...",Rural,76.76,897.65,19,833,0.3949,100.00,0.84,97.15,3.9,48.3

This dataset contains ten columns:
- `county`: The name of the county in Rhode Island.
- `geometry`: a description of the geometry of the county, used for map visualizations.
- `rural_urban`: a statistical classification of whether a county is more rural or urban.
- `life_expectancy`: the average life expectancy in the county.
- `asmr`: age-standardized mortality rate (ASMR) per 100,000, or the number of people who die every year, weighted to enable comparisons across different age distributions.
- `asmr_rank`: the ASMR rank across all counties (1 is the lowest ASMR).
- `rent`: The median rent in the county.
- `gini`: The [Gini coefficient](https://en.wikipedia.org/wiki/Gini_coefficient), a measure of wealth inequality in the county.
- `pct_food_desert`: The percentage of the population in the county that lives in a USDA-defined [food desert](https://en.wikipedia.org/wiki/Food_desert).
- `fast_food`: The number of fast food and convenience stores per square mile in the county.
- `pct_farmers_market`: The percentage of the population that lives within 10 minutes of a farmer's market.

# Part B. Critique

The general structure of this assignment is that each task focuses on a subset of columns in one of the datasets, and the challenge is to pick an expressive and effective visualization of those variables. In Part B, we will give you three visualizations, and you have to pick one and justify your reasoning. In Part C, you will write your own visualization on the same dataset, while Part D will see you exploring one of your choice and creating another.

For the critique, you should write ≤2 paragraphs justifying your selection using the concepts we discussed in lecture. Focus on the extent to which each visualization is *expressive* (accurately communicates the underlying data) and *effective* (encodes data to maximally leverage human perception). Each visualization will have relative strengths and weaknesses. 

There is not necessarily an objectively correct answer to each question, and you may find your personal preference diverges from which visualization achieves the two goals as defined in the vocabulary of the class—the correct answer may not even be the visualization we'd write if we had the choice! That said, you should articulate what types of comparisons you think are most germane to the question at hand and which visualizations support them best.

## Task 1: Is Rhode Island the Dunkin's capital of the world? (10 points)

This task focuses on the `state`, `store_count`, `stores_per_sqmi`, and `stores_per_100k` variables to analyze whether Rhode Island can claim to be the Dunkin's capital of the world.

### Chart 1A

In [ ]:
base = alt.Chart(dunkins).encode(x="state:N")
base.mark_point(filled=True).encode(size="store_count", color="stores_per_sqmi") + \
base.mark_point(filled=False).encode(size="store_count", strokeWidth="stores_per_100k")

alt.LayerChart(...)

### Chart 1B

In [ ]:
base.mark_bar().encode(y="stores_per_100k:Q", size="store_count:Q", color="region") + \
base.mark_point().encode(y="stores_per_100k:Q", yOffset=alt.value(-10), opacity="stores_per_sqmi")

alt.LayerChart(...)

### Chart 1C

In [ ]:
graph3 = alt.Chart(dunkins).encode(y="state:N")
(
    graph3.mark_point(filled=False).encode(x="stores_per_100k", size=alt.value(260), strokeWidth=alt.value(3), color=alt.value("#111")) + \
    graph3.mark_point(filled=True).encode(x="stores_per_100k", size=alt.value(90), color=alt.value("white")) + \
    graph3.mark_point(filled=True).encode(x="stores_per_100k", xOffset=alt.value(20), opacity=alt.value(0.7), size="stores_per_sqmi")
).properties(width=800, height=450)

alt.LayerChart(...)

### Task 1 answer

*Your answer here.*

## Task 2: How does housing affordability relate to ASMR? (10 points)

This tasks focuses on the `asmr`, `rent`, `gini`, and `rural_urban` variables to analyze how the age-standardized mortality rate relates to a county's rent and Gini coefficient, considering the distinction between rural and urban counties.

### Chart 2A

In [ ]:
chart = alt.Chart(life)
chart.mark_point().encode(
    x=alt.X("rent", scale=alt.Scale(zero=False)),
    y=alt.Y("asmr", scale=alt.Scale(zero=False)),
    size="gini",
    shape="rural_urban"
)

alt.Chart(...)

### Chart 2B

In [ ]:
chart.mark_bar().encode(x="rent", y="asmr", row="rural_urban", color="gini")

alt.Chart(...)

### Chart 2C

In [ ]:
(
    chart.mark_line().encode(x="asmr_rank", y=alt.Y("rent", scale=alt.Scale(zero=False)), color="rural_urban") &
    chart.mark_line().encode(x="asmr_rank", y=alt.Y("gini", scale=alt.Scale(zero=False)), color="rural_urban")
)

alt.VConcatChart(...)

### Task 2 Answer

*Your answer here.*

## Task 3: How does life expectancy vary across Rhode Island? (10 points)

This task focuses on the `county`, `life_expectancy`, and `rural_urban` variables to analyze how life expectancy changes county-by-county, with an aggregate focus on comparing rural vs. urban counties.

### Chart 3A

In [ ]:
alt.Chart(life).mark_bar().encode(
    x=alt.X("county", sort="-y"), 
    y=alt.Y("life_expectancy:Q", scale=alt.Scale(domainMin=75, clamp=True)), 
    color="rural_urban"
)

alt.Chart(...)

### Chart 3B

Note that this chart contains a tooltip &mdash; try hovering your mouse over each county.

In [ ]:
hover = alt.selection_point(on='mouseover', empty=False)
geo_base = alt.Chart(life).mark_geoshape() \
    .project(type="identity", reflectY=True) \
    .encode(strokeWidth=alt.condition(hover, alt.value(5.), alt.value(1.)), stroke=alt.value("#ccc")).add_params(hover) \
    .properties(width=600, height=600)

geo_base.encode(color="life_expectancy", tooltip=["county", "life_expectancy", "rural_urban"])

alt.Chart(...)

### Chart 3C

Note that this chart contains a selection interval &mdash; click and drag your mouse within the bar chart below.

In [ ]:
brush = alt.selection_interval(encodings=['x'])
geo_base.encode(
    color="rural_urban", 
    tooltip=["county", "life_expectancy"], 
    opacity=alt.condition(brush, alt.value(1.0), alt.value(0.3))
) & \
alt.Chart(life).mark_bar().encode(
    x=alt.X("county:N", sort='-y'), 
    y=alt.Y("life_expectancy:Q", scale=alt.Scale(domainMin=75, clamp=True))
).add_params(brush)

alt.VConcatChart(...)

### Task 3 Answer

*Your answer here.*

# Part C: Generation

Like the previous part, each task asks you to focus on a subset of variables. Your challenge is to write an Altair program which you think best visualizes those variables, and to write ~1 paragraph explaining your reasoning. 

Hopefully, you attended lab and familiarized yourself with Altair. If not, the material from it can be found in our lab repo, which is linked on the EdStem!

For additional resources, check out the Altair documentation (https://altair-viz.github.io/). You can also see some examples in the code blocks from Part B above. Some particular pages you'll find useful:

- **Examples:** https://altair-viz.github.io/user_guide/marks/index.html
- **Marks:** https://altair-viz.github.io/user_guide/marks/index.html
- **Encodings:** https://altair-viz.github.io/user_guide/encodings/index.html

You should put some effort into tailoring the visualization for the particular variables and question being visualized, rather than just using the default visualization for a particular encoding. For instance, you should consider the axis scale, the position of the legend / text annotations, and redundant encoding of information. Your justification should be stated using the vocabulary of the course, like your responses to part B.

## Task 4: Which states and regions have most Dunkin's? (10 points)

This task should focus on `store_count`, `state`, and `region`.

In [ ]:
# YOUR ANSWER HERE

### Task 4 Reasoning

*Your answer here.*

## Task 5: How does food access relate to life expectancy? (10 points)

This task should focus on the `pct_food_desert`, `pct_farmers_market`, `fast_food`, and `life_expectancy` variables.

In [ ]:
# YOUR ANSWER HERE

### Task 5 Reasoning

*Your answer here.*

## Task 6: How does educational attainment relate to life expectancy? (25 points)

This task should focus on `pct_less_hs`, `pct_bachelors`, and `life_expectancy`. For this question, your visualization should support interactive queries that ask: for a cluster of towns with similar levels of educational attainment, how does their distribution of life expectancy differ from other towns? Check out Altair's [Interactive charts](https://altair-viz.github.io/gallery/index.html#interactive-charts) gallery for examples of possible interactions to implement.

In [ ]:
# YOUR ANSWER HERE

### Task 6 Reasoning

*Your answer here.*

# Part D: Visualization Exploration

For this part, you will play the role of a data journalist. The file `datasets.md` has ten curated datasets from Tidy Tuesday, a weekly data science and visualization challenge, and scripts to fetch their contents into tidied dataframes.

Your goal is to answer a question—of your creation or from the sample questions on each dataset—with a visualization using pertinent data to your question. **Your visualization must use at least four variables and make use of one of the techniques of: redundant encoding, faceting/composition, or interactivity.**

You should write a <= 2-paragraph explanation of your visualization, illustrating how it _expresses_ the relevant data to your question, how _effective_ it is at answering your question, and what the result of the visualization tells you about the data story being told.

## Datasets!

Find our dataset samples in `datasets.md`. **You should put the fetching/tidying script for your dataset at the top of the code cell below.**

### Task 7: Data Journalism (25 Points)

Your reasoning should state plainly the dataset you investigated, the question you chose to answer, the variables you chose to encode and why, and the choices you made in your visualization to effectively encode those variables and how they answer your question. This task is purposely open-ended, so you will be graded on the quality of the explanation's justification of your visualization, with extra points being afforded to those who make their own questions or make especially appealing and creative visualizations.

### Task 7 Code:

In [ ]:
# TODO: PUT YOUR DATASET FETCH SCRIPT HERE

# YOUR ANSWER HERE

### Task 7 Reasoning:

_Your answer here._